### ISSUE TITLE
Compact Raid Frames

### ISSUE THREAD

**Issue by Oshire** [samueladamsonline/Lorti-UI-TBC#10]
Hello! fresh install, no other addons running. Lua Error when i enter the game.

Message: Interface\AddOns\Lorti-UI-TBC\core\frames.lua:129: attempt to index global 'CompactRaidFrameContainerBorderFrame' (a nil value)
Time: Tue May 25 16:38:44 2021
Count: 1
Stack: Interface\AddOns\Lorti-UI-TBC\core\frames.lua:129: attempt to index global 'CompactRaidFrameContainerBorderFrame' (a nil value)
[string "@Interface\AddOns\Lorti-UI-TBC\core\frames.lua"]:129: in function `ColorRaid'
[string "@Interface\AddOns\Lorti-UI-TBC\core\frames.lua"]:137: in function <Interface\AddOns\Lorti-UI-TBC\core\frames.lua:136>

Locals: (*temporary) = <function> defined =[C]:-1
(*temporary) = <table> {
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = 5
(*temporary) = 5
(*temporary) = 1
(*temporary) = 5
(*temporary) = nil
(*temporary) = nil
(*temporary) = "CompactRaidFrame5"
(*temporary) = "5"
(*temporary) = "5"
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index global 'CompactRaidFrameContainerBorderFrame' (a nil value)"

**Comment by Oshire** [comment]
UPDATE! That ERROR only appears on a iMac, on windows it works just fine.

**Comment by samueladamsonline** [comment]
Thanks for the update @Oshire. This is on my radar to look into but is low priority at the moment.
