### ISSUE TITLE
Contrast for text of ranks in the Spellbook unreadable

### ISSUE THREAD

**Issue by kevhardy** [samueladamsonline/Lorti-UI-TBC#13]
The text for the ranks in the spellbook is really hard to read. This isn't a huge problem but figured it's probably an easy fix.

![image](https://user-images.githubusercontent.com/12358277/119868647-ec3a5980-bee4-11eb-9ec9-0f26d508c6e1.png)

Here's a example of what I'm talking about. You can barely make out most of the ranks and the top right spell rank is almost non existent.  Would be great if you could make it stand out a bit more.

**Comment by samueladamsonline** [comment]
Hey @kevhardy, thanks for mentioning this. I have also noticed this. I've pushed a fix for this. Please update Lorti UI via CurseForge. Thanks again for using the addon.
