### ISSUE TITLE
Ui blocks detachment of buffs from map

### ISSUE THREAD

**Issue by Carpathea** [samueladamsonline/Lorti-UI-TBC#16]
I cant use leatrix plus or sexy map to detach buffs from the map

![image](https://user-images.githubusercontent.com/41167158/120040596-c4d7af80-bffe-11eb-90ea-8cced247d456.png)

is there anywhere in the code that allows me to do this or can this be a feature?

**Comment by Carpathea** [comment]
--hook Blizzard functions
  hooksecurefunc("BuffFrame_UpdateAllBuffAnchors", updateAllBuffAnchors)
  hooksecurefunc("DebuffButton_UpdateAnchors", updateDebuffAnchors)
  in updateallbuffanchors and devbuffanchors somewhere it locks its position to the map, im not good enough at lua to figure out where though

**Comment by samueladamsonline** [comment]
Hi @Carpathea, Leatrix Plus and Sexy Map are not supported by Lorti UI. I'll add this issue to my list of things to look at, but I have quite a few higher priority issues I'll be attempting to address first in turn. Thanks for the code block also. I'll take a closer look when I get a chance.

**Comment by XyzKangUI** [comment]
This https://pastebin.com/GVJrMLbh would allow you to use scripts, moveanything or leatrix plus to move bufframe. @Carpathea @samueladamsonline 

Basically stripped out all anchor related stuff.
