### ISSUE TITLE
Elite Target Frames are not working

### ISSUE THREAD

**Issue by Moki182** [samueladamsonline/Lorti-UI-TBC#18]
Hi

Elite Target Frames are not working when UnitframesImproved addon is enabled.
Here how its look like:

https://imgur.com/a/qIi2BvJ

Could you fix this?

**Comment by samueladamsonline** [comment]
Hi @Moki182, Lorti UI does not currently support UnitFramesImproved. I'll add this to my list of possible enhanced, but cannot guarantee support in the future. Stay tuned for any updates which may address this issue.
