### ISSUE TITLE
White rectangular boxes in upper corner of ability when targeting someone / something

### ISSUE THREAD

**Issue by wowiemaui** [samueladamsonline/Lorti-UI-TBC#23]
I'm getting these small white rectangular boxes in the upper right hand corner of abilities when I target another player / NPC / Enemy. I have edited the files to remove keybind text / macro text but can't seem to find a way to get rid of these little boxes. https://imgur.com/1UMK7Zo

**Comment by samueladamsonline** [comment]
Issue already reported and tracked.
